[package]
name = "basic"
version = "0.1.0"
authors = ["Łukasz Biel <lukasz.p.biel@gmail.com>"]
edition = "2018"

[lib]
name = "basic"
path = "src/lib.rs"
doctest = false

[dev-dependencies]
test-case = { path = "../../crates/test-case" }
pretty_assertions = "1.0.0"

[workspace]
