[package]
name = "test_item_reuse"
version = "0.1.0"
edition = "2018"

[lib]
name = "test_item_reuse"
path = "src/lib.rs"
doctest = false

[dependencies]
test-case = { path = "../../crates/test-case" }

[workspace]
